PROMPT='%F{2}%1~ %B%F{4}[%f%b '
RPROMPT='%B%F{3}$(git_prompt_info) %F{4}] %(?:%F{6}:%F{1})%T%f%b'

ZSH_THEME_GIT_PROMPT_PREFIX=""
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_CLEAN=" %F{2}✓"
ZSH_THEME_GIT_PROMPT_DIRTY=" %F{1}✗"
