### VARIABLES
export EDITOR="nvim"
export GPG_TTY=$TTY
export NODE_OPTIONS="--max-old-space-size=4096"
export PATH="$PATH:/home/carlo/.cargo/bin"
export PATH="$PATH:/home/carlo/.local/bin"
export PATH="$PATH:/home/carlo/.yarn/bin"
export XZ_DEFAULTS="-T0"

### OMZ
export ZSH="/home/carlo/.oh-my-zsh"
zstyle ':omz:plugins:yarn' global-path off
ZSH_DISABLE_COMPFIX="true"
ZSH_THEME="nt-modif"
plugins=(colored-man-pages deno git git-prompt rbw sudo yarn z)
source $ZSH/oh-my-zsh.sh
less_termcap[so]="${fg_bold[yellow]}${bg[black]}"

### KITTY SHELL INTEGRATION
if test -n "$KITTY_INSTALLATION_DIR"; then
  export KITTY_SHELL_INTEGRATION="no-rc no-cursor"
  autoload -Uz -- "$KITTY_INSTALLATION_DIR"/shell-integration/zsh/kitty-integration
  kitty-integration
  unfunction kitty-integration
fi

### ALIASES
alias c="clear"
alias e="exit"
alias l="exa -la --group-directories-first --icons"
alias s="sudo"
alias bc="bc -l"
alias cdot="~/Documents/dev/dotfiles/copyconfig.sh"
alias icat="kitty +kitten icat"
alias lg="lazygit"
alias mosh="mosh --ssh='kitty +kitten ssh'"
alias sage="sage --notebook=jupyter"
alias ssh="kitty +kitten ssh"
alias sva="sudo surfshark-vpn attack"
alias svd="sudo surfshark-vpn down"
alias v="openNvim"
