### VARIABLES
export EDITOR="nvim"
export GPG_TTY=$TTY
export PATH="$PATH:/home/carlo/.cargo/bin"
export PATH="$PATH:/home/carlo/.local/bin"
export ZSHZ_CASE=ignore
export XZ_DEFAULTS="-T0"

### OMZ
export ZSH="/home/carlo/.oh-my-zsh"
ZSH_THEME="nt-modif"
plugins=(aliases colored-man-pages deno git git-prompt rbw sudo yarn zsh-z)
source $ZSH/oh-my-zsh.sh
less_termcap[so]="${fg_bold[yellow]}${bg[black]}"

### ALIASES
alias c="clear"
alias e="exit"
alias l="exa -la --group-directories-first --icons"
alias s="sudo"
alias bc="bc -l"
alias cdot="~/Documents/dev/dotfiles/copyconfig.sh"
alias torrentrackers="curl -s https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best_ip.txt | clipcopy"
alias icat="kitty +kitten icat"
alias ldk="lazydocker"
alias lg="lazygit"
alias sage="sage --notebook=jupyter"
alias ssh="kitty +kitten ssh"
alias v="openNvim"
